package com.cfido.snapshot.domain;
// Generated by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Mail
 * 
 * @auther <a href="https://github.com/liangwj72">Alex </a>
 */
@Entity
@Table(name = "mail", uniqueConstraints = @UniqueConstraint(columnNames = "msg_id"))
public class Mail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Date createDate;
	private String mailTo;
	private String mailFrom;
	private String subj;
	private String area;
	private String msgId;
	private String oldReply;
	private String pid;
	private String chrs;
	private String eid;
	private String tid;
	private String msg;
	private String path;
	private int replays;
	private int msgLen;
	private String originMsgId;
	private int areaId;

	public Mail() {
	}

	public Mail(Date createDate, String mailTo, String mailFrom, String subj, String area, String msgId, int replays, int msgLen,
			int areaId) {
		this.createDate = createDate;
		this.mailTo = mailTo;
		this.mailFrom = mailFrom;
		this.subj = subj;
		this.area = area;
		this.msgId = msgId;
		this.replays = replays;
		this.msgLen = msgLen;
		this.areaId = areaId;
	}

	public Mail(Date createDate, String mailTo, String mailFrom, String subj, String area, String msgId, String oldReply,
			String pid, String chrs, String eid, String tid, String msg, String path, int replays, int msgLen, String originMsgId,
			int areaId) {
		this.createDate = createDate;
		this.mailTo = mailTo;
		this.mailFrom = mailFrom;
		this.subj = subj;
		this.area = area;
		this.msgId = msgId;
		this.oldReply = oldReply;
		this.pid = pid;
		this.chrs = chrs;
		this.eid = eid;
		this.tid = tid;
		this.msg = msg;
		this.path = path;
		this.replays = replays;
		this.msgLen = msgLen;
		this.originMsgId = originMsgId;
		this.areaId = areaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "mail_to", nullable = false, length = 50)
	public String getMailTo() {
		return this.mailTo;
	}

	public void setMailTo(String mailTo) {
		this.mailTo = mailTo;
	}

	@Column(name = "mail_from", nullable = false, length = 50)
	public String getMailFrom() {
		return this.mailFrom;
	}

	public void setMailFrom(String mailFrom) {
		this.mailFrom = mailFrom;
	}

	@Column(name = "subj", nullable = false, length = 100)
	public String getSubj() {
		return this.subj;
	}

	public void setSubj(String subj) {
		this.subj = subj;
	}

	@Column(name = "area", nullable = false, length = 50)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "msg_id", unique = true, nullable = false, length = 50)
	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	@Column(name = "old_reply", length = 50)
	public String getOldReply() {
		return this.oldReply;
	}

	public void setOldReply(String oldReply) {
		this.oldReply = oldReply;
	}

	@Column(name = "pid", length = 50)
	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "chrs", length = 50)
	public String getChrs() {
		return this.chrs;
	}

	public void setChrs(String chrs) {
		this.chrs = chrs;
	}

	@Column(name = "eid", length = 50)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Column(name = "tid", length = 50)
	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	@Column(name = "msg")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(name = "path", length = 50)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "replays", nullable = false)
	public int getReplays() {
		return this.replays;
	}

	public void setReplays(int replays) {
		this.replays = replays;
	}

	@Column(name = "msg_len", nullable = false)
	public int getMsgLen() {
		return this.msgLen;
	}

	public void setMsgLen(int msgLen) {
		this.msgLen = msgLen;
	}

	@Column(name = "origin_msg_id", length = 50)
	public String getOriginMsgId() {
		return this.originMsgId;
	}

	public void setOriginMsgId(String originMsgId) {
		this.originMsgId = originMsgId;
	}

	@Column(name = "area_id", nullable = false)
	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

}
