package com.cfido.snapshot.domain;
// Generated by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mail
 * 
 * @auther <a href="https://github.com/liangwj72">Alex </a>
 */
@Entity
@Table(name = "mail")
public class Mail implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String LMsgid;
	private Date LDate;
	private String LTo;
	private String LFrom;
	private String LSubj;
	private String LArea;
	private String LReply;
	private String LPid;
	private String LChrs;
	private String LEid;
	private String LTid;
	private String LMsg;
	private String LPath;
	private int replays;
	private int msgLen;
	private String originMsgId;

	public Mail() {
	}

	public Mail(String LMsgid, Date LDate, String LTo, String LFrom, String LSubj, String LArea, int replays, int msgLen) {
		this.LMsgid = LMsgid;
		this.LDate = LDate;
		this.LTo = LTo;
		this.LFrom = LFrom;
		this.LSubj = LSubj;
		this.LArea = LArea;
		this.replays = replays;
		this.msgLen = msgLen;
	}

	public Mail(String LMsgid, Date LDate, String LTo, String LFrom, String LSubj, String LArea, String LReply, String LPid,
			String LChrs, String LEid, String LTid, String LMsg, String LPath, int replays, int msgLen, String originMsgId) {
		this.LMsgid = LMsgid;
		this.LDate = LDate;
		this.LTo = LTo;
		this.LFrom = LFrom;
		this.LSubj = LSubj;
		this.LArea = LArea;
		this.LReply = LReply;
		this.LPid = LPid;
		this.LChrs = LChrs;
		this.LEid = LEid;
		this.LTid = LTid;
		this.LMsg = LMsg;
		this.LPath = LPath;
		this.replays = replays;
		this.msgLen = msgLen;
		this.originMsgId = originMsgId;
	}

	@Id

	@Column(name = "l_msgid", unique = true, nullable = false, length = 50)
	public String getLMsgid() {
		return this.LMsgid;
	}

	public void setLMsgid(String LMsgid) {
		this.LMsgid = LMsgid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "l_date", nullable = false, length = 19)
	public Date getLDate() {
		return this.LDate;
	}

	public void setLDate(Date LDate) {
		this.LDate = LDate;
	}

	@Column(name = "l_to", nullable = false, length = 50)
	public String getLTo() {
		return this.LTo;
	}

	public void setLTo(String LTo) {
		this.LTo = LTo;
	}

	@Column(name = "l_from", nullable = false, length = 50)
	public String getLFrom() {
		return this.LFrom;
	}

	public void setLFrom(String LFrom) {
		this.LFrom = LFrom;
	}

	@Column(name = "l_subj", nullable = false, length = 100)
	public String getLSubj() {
		return this.LSubj;
	}

	public void setLSubj(String LSubj) {
		this.LSubj = LSubj;
	}

	@Column(name = "l_area", nullable = false, length = 50)
	public String getLArea() {
		return this.LArea;
	}

	public void setLArea(String LArea) {
		this.LArea = LArea;
	}

	@Column(name = "l_reply", length = 50)
	public String getLReply() {
		return this.LReply;
	}

	public void setLReply(String LReply) {
		this.LReply = LReply;
	}

	@Column(name = "l_pid", length = 50)
	public String getLPid() {
		return this.LPid;
	}

	public void setLPid(String LPid) {
		this.LPid = LPid;
	}

	@Column(name = "l_chrs", length = 50)
	public String getLChrs() {
		return this.LChrs;
	}

	public void setLChrs(String LChrs) {
		this.LChrs = LChrs;
	}

	@Column(name = "l_eid", length = 50)
	public String getLEid() {
		return this.LEid;
	}

	public void setLEid(String LEid) {
		this.LEid = LEid;
	}

	@Column(name = "l_tid", length = 50)
	public String getLTid() {
		return this.LTid;
	}

	public void setLTid(String LTid) {
		this.LTid = LTid;
	}

	@Column(name = "l_msg")
	public String getLMsg() {
		return this.LMsg;
	}

	public void setLMsg(String LMsg) {
		this.LMsg = LMsg;
	}

	@Column(name = "l_path", length = 50)
	public String getLPath() {
		return this.LPath;
	}

	public void setLPath(String LPath) {
		this.LPath = LPath;
	}

	@Column(name = "replays", nullable = false)
	public int getReplays() {
		return this.replays;
	}

	public void setReplays(int replays) {
		this.replays = replays;
	}

	@Column(name = "msg_len", nullable = false)
	public int getMsgLen() {
		return this.msgLen;
	}

	public void setMsgLen(int msgLen) {
		this.msgLen = msgLen;
	}

	@Column(name = "origin_msg_id", length = 50)
	public String getOriginMsgId() {
		return this.originMsgId;
	}

	public void setOriginMsgId(String originMsgId) {
		this.originMsgId = originMsgId;
	}

}
