package com.cfido.snapshot.domain;
// Generated by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users
 * 
 * @auther <a href="https://github.com/liangwj72">Alex </a>
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String userName;
	private int mailNum;

	public Users() {
	}

	public Users(String userName, int mailNum) {
		this.userName = userName;
		this.mailNum = mailNum;
	}

	@Id

	@Column(name = "user_name", unique = true, nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "mail_num", nullable = false)
	public int getMailNum() {
		return this.mailNum;
	}

	public void setMailNum(int mailNum) {
		this.mailNum = mailNum;
	}

}
